// redux/actionTypes.js

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const SELECT_ITEM = "SELECT_ITEM";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_CART_DATA_SUCCESS = "FETCH_CART_DATA_SUCCESS";
export const FETCH_CART_DATA_FAILURE = "FETCH_CART_DATA_FAILURE";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
